on: [push]
name: CI image-compressor
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v2
      - run: stack setup
      - run: make
      - run: make re
      - run: make clean
      - run: make fclean
